/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Board: typeof import('./src/components/board.vue')['default']
    ConfirmDialog: typeof import('./src/components/confirmDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Task: typeof import('./src/components/taskCard.vue')['default']
    TaskCard: typeof import('./src/components/taskCard.vue')['default']
    UpdateTaskDialog: typeof import('./src/components/updateTaskDialog.vue')['default']
  }
}
